name: ci
run-name: Continuous Integration
on:
  push:

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1
      - name: Build
        run: cargo build --verbose
      - name: Clippy
        run: cargo clippy --all-targets --all-features 
      - name: Test
        run: cargo test --verbose


